<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select card statusPendingApprovedSen_3d59c9</name>
   <tag></tag>
   <elementGuidId>a711229b-d56b-41a3-bd9c-5c21b134bf5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card_info_filter_status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='card_info_filter_status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>28414228-a94d-4669-8e46-b13181da75da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_info_filter_status</value>
      <webElementGuid>88715ef0-e86b-47c8-b702-b80feb6dd7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_info_filter[status]</value>
      <webElementGuid>22b00b12-2388-4e8d-a8e2-503c2bc391b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>012d9701-cd08-48d3-80c3-10dab22344ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select card statusPendingApprovedSend To SWITCHReceived From SWITCHCard DispatchCard AcknowledgeCard MigratedCard Migrated Before DispatchPin AcknowledgeCard DeliveredPin DeliveredActivatedBlock PendingBlock VerifiedBlockedUnblock PendingUnblock VerifiedExpiredDestroyed</value>
      <webElementGuid>d7c36f49-dc5c-4d7a-a110-00690175299f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_info_filter_status&quot;)</value>
      <webElementGuid>125c6ab5-b5b7-4820-b913-49386e996b33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='card_info_filter_status']</value>
      <webElementGuid>67c27cbd-2a74-47e6-88bc-d967d92a5ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card_info_filter']/div[6]/select</value>
      <webElementGuid>9050b631-4d1f-4215-9dda-e9bcaf2c6604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Status'])[1]/following::select[1]</value>
      <webElementGuid>ced5b790-4c33-4b0d-af6b-4199b6c28ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Code'])[1]/following::select[1]</value>
      <webElementGuid>c6052561-a4e6-461b-93a4-2cc5db4adb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Remarks'])[1]/preceding::select[1]</value>
      <webElementGuid>82d25bc3-16bb-42bf-8d68-7cc2264d7347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Types'])[1]/preceding::select[2]</value>
      <webElementGuid>f5deefee-de09-4dfd-b20b-adf38a33c7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>45c6ff71-d9cb-4680-af40-13807c8e07a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'card_info_filter_status' and @name = 'card_info_filter[status]' and (text() = 'Select card statusPendingApprovedSend To SWITCHReceived From SWITCHCard DispatchCard AcknowledgeCard MigratedCard Migrated Before DispatchPin AcknowledgeCard DeliveredPin DeliveredActivatedBlock PendingBlock VerifiedBlockedUnblock PendingUnblock VerifiedExpiredDestroyed' or . = 'Select card statusPendingApprovedSend To SWITCHReceived From SWITCHCard DispatchCard AcknowledgeCard MigratedCard Migrated Before DispatchPin AcknowledgeCard DeliveredPin DeliveredActivatedBlock PendingBlock VerifiedBlockedUnblock PendingUnblock VerifiedExpiredDestroyed')]</value>
      <webElementGuid>f3c9a221-3060-48ff-be20-02a2b4c0a820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
